require('dotenv').config();
const { Telegraf } = require('telegraf');
const axios = require('axios');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const { promisify } = require('util');
const execAsync = promisify(exec);
const { initMonitor, runAllChecks, getStatusReport } = require('./monitor');

// ─── CONFIG ───────────────────────────────────────────────────────────────────
const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);
const OWNER_ID = parseInt(process.env.TELEGRAM_OWNER_ID);
const BASE_URL = process.env.OPENAI_BASE_URL;
const API_KEY = process.env.OPENAI_API_KEY;
const DEFAULT_MODEL = process.env.DEFAULT_MODEL || 'nvidia/meta/llama-3.3-70b-instruct';
const WALLET_FILE = path.join(__dirname, 'wallets.json');
const MEMORY_FILE = path.join(__dirname, 'memory.json');
const MAX_HISTORY = 20; // maksimal pesan yang diingat

console.log('[Hermes] Bot starting...');
console.log(`[Hermes] Owner: ${OWNER_ID}`);
console.log(`[Hermes] Model: ${DEFAULT_MODEL}`);

// ─── MEMORY / HISTORY ─────────────────────────────────────────────────────────
function loadMemory() {
  try {
    if (fs.existsSync(MEMORY_FILE)) {
      return JSON.parse(fs.readFileSync(MEMORY_FILE, 'utf8'));
    }
  } catch (e) {}
  return [];
}

function saveMemory(history) {
  try {
    // Simpan hanya MAX_HISTORY pesan terakhir
    const trimmed = history.slice(-MAX_HISTORY);
    fs.writeFileSync(MEMORY_FILE, JSON.stringify(trimmed, null, 2));
    return trimmed;
  } catch (e) {
    return history;
  }
}

function clearMemory() {
  try { fs.writeFileSync(MEMORY_FILE, '[]'); } catch (e) {}
}

// ─── WALLET HELPERS ───────────────────────────────────────────────────────────
function loadWallets() {
  try {
    if (fs.existsSync(WALLET_FILE)) {
      return JSON.parse(fs.readFileSync(WALLET_FILE, 'utf8'));
    }
  } catch (e) {}
  return [];
}

function saveWallet(wallet) {
  const wallets = loadWallets();
  wallets.push({ ...wallet, createdAt: new Date().toISOString() });
  fs.writeFileSync(WALLET_FILE, JSON.stringify(wallets, null, 2));
}

// ─── TOOL: JALANKAN BASH ──────────────────────────────────────────────────────
async function runShell(command, timeoutMs = 30000) {
  try {
    const { stdout, stderr } = await execAsync(command, {
      timeout: timeoutMs,
      maxBuffer: 1024 * 1024 * 5 // 5MB
    });
    return stdout || stderr || '(no output)';
  } catch (err) {
    return `[ERROR] ${err.message}`;
  }
}

// ─── TOOL: BUAT WALLET ETHEREUM ───────────────────────────────────────────────
async function createEthWallet(label = '') {
  // Gunakan node crypto untuk generate key pair sederhana
  // (tanpa ethers.js — pakai openssl saja)
  const { stdout } = await execAsync(
    'node -e "const crypto=require(\'crypto\');' +
    'const {privateKey}=crypto.generateKeyPairSync(\'ec\',{namedCurve:\'secp256k1\'});' +
    'const pk=privateKey.export({type:\'sec1\',format:\'der\'}).toString(\'hex\');' +
    'console.log(JSON.stringify({privateKey:pk.substring(14,78)}));"'
  );
  const data = JSON.parse(stdout.trim());
  const wallet = {
    label: label || `wallet_${Date.now()}`,
    privateKey: data.privateKey,
    note: 'Generated by Hermes Agent'
  };
  saveWallet(wallet);
  return wallet;
}

// ─── SYSTEM PROMPT ────────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `Kamu adalah Hermes, AI agent yang berjalan di VPS Linux.
Kamu bisa melakukan berbagai tugas nyata, bukan hanya chat.

KEMAMPUAN KAMU:
1. Jalankan perintah bash/shell di VPS
2. Clone repo, manage file dan direktori  
3. Buat dan simpan wallet crypto
4. Bantu otomasi task di web (berikan instruksi curl/script)
5. Ingat percakapan sebelumnya

FORMAT PERINTAH KHUSUS (gunakan ini untuk eksekusi):
- Untuk jalankan shell: tulis blok \`\`\`shell\n<command>\n\`\`\` di responsmu
- Untuk buat wallet: tulis \`\`\`create_wallet\n<label>\n\`\`\`
- Untuk lihat daftar wallet: tulis \`\`\`list_wallets\`\`\`
- Untuk hapus memory: tulis \`\`\`clear_memory\`\`\`

PENTING:
- Kamu hanya melayani owner yang sudah diotorisasi
- Selalu konfirmasi sebelum menjalankan perintah destruktif (rm -rf, dll)
- Simpan semua wallet yang dibuat ke file wallets.json
- Jawab dalam bahasa Indonesia kecuali diminta lain`;

// ─── PARSE & EKSEKUSI TOOL DARI RESPONSE AI ──────────────────────────────────
async function parseAndExecuteTools(aiText) {
  let finalText = aiText;
  const toolOutputs = [];

  // 1. Shell execution
  const shellRegex = /```shell\n([\s\S]*?)```/g;
  let match;
  while ((match = shellRegex.exec(aiText)) !== null) {
    const command = match[1].trim();
    console.log(`[SHELL] Executing: ${command}`);
    const output = await runShell(command);
    toolOutputs.push(`\n⚡ *Shell:* \`${command}\`\n\`\`\`\n${output.substring(0, 2000)}\n\`\`\``);
    finalText = finalText.replace(match[0], '');
  }

  // 2. Create wallet
  const walletRegex = /```create_wallet\n([\s\S]*?)```/g;
  while ((match = walletRegex.exec(aiText)) !== null) {
    const label = match[1].trim();
    console.log(`[WALLET] Creating wallet: ${label}`);
    try {
      const wallet = await createEthWallet(label);
      toolOutputs.push(`\n💰 *Wallet dibuat:*\n• Label: ${wallet.label}\n• Private Key: \`${wallet.privateKey}\`\n• ⚠️ Simpan private key ini baik-baik!`);
    } catch (e) {
      toolOutputs.push(`\n❌ Gagal buat wallet: ${e.message}`);
    }
    finalText = finalText.replace(match[0], '');
  }

  // 3. List wallets
  if (aiText.includes('```list_wallets```')) {
    const wallets = loadWallets();
    if (wallets.length === 0) {
      toolOutputs.push('\n📭 Belum ada wallet tersimpan.');
    } else {
      const list = wallets.map((w, i) =>
        `${i + 1}. *${w.label}* — \`${w.privateKey.substring(0, 8)}...\` (${w.createdAt})`
      ).join('\n');
      toolOutputs.push(`\n💼 *Daftar Wallet (${wallets.length}):*\n${list}`);
    }
    finalText = finalText.replace('```list_wallets```', '');
  }

  // 4. Clear memory
  if (aiText.includes('```clear_memory```')) {
    clearMemory();
    toolOutputs.push('\n🧹 Memory percakapan dihapus.');
    finalText = finalText.replace('```clear_memory```', '');
  }

  return {
    text: finalText.trim(),
    toolOutputs
  };
}

// ─── KIRIM KE LLM ─────────────────────────────────────────────────────────────
async function askLLM(userMessage, history) {
  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
    ...history,
    { role: 'user', content: userMessage }
  ];

  const response = await axios.post(`${BASE_URL}/chat/completions`, {
    model: DEFAULT_MODEL,
    messages,
    max_tokens: 1500,
    temperature: 0.7
  }, {
    headers: { Authorization: `Bearer ${API_KEY}` },
    timeout: 60000
  });

  return response.data.choices[0].message.content;
}

// ─── COMMANDS ─────────────────────────────────────────────────────────────────
bot.start((ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  ctx.reply('👋 Halo! Hermes Agent aktif.\n\nKemampuan:\n• 🖥️ Jalankan bash command\n• 📁 Manage file & repo\n• 💰 Buat wallet crypto\n• 🧠 Ingat percakapan\n• 🌐 Bantu otomasi web\n\nKirim pesan atau perintah apa saja!');
});

bot.command('model', (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  ctx.reply(`🤖 Model aktif: \`${DEFAULT_MODEL}\``, { parse_mode: 'Markdown' });
});

bot.command('memory', (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  const history = loadMemory();
  ctx.reply(`🧠 Memory: ${history.length} pesan tersimpan (max ${MAX_HISTORY})`);
});

bot.command('clearmemory', (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  clearMemory();
  ctx.reply('🧹 Memory dihapus!');
});

bot.command('wallets', (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  const wallets = loadWallets();
  if (wallets.length === 0) return ctx.reply('📭 Belum ada wallet tersimpan.');
  const list = wallets.map((w, i) =>
    `${i + 1}. *${w.label}*\n   PK: \`${w.privateKey.substring(0, 12)}...\`\n   ${w.createdAt}`
  ).join('\n\n');
  ctx.reply(`💼 *Wallet tersimpan (${wallets.length}):*\n\n${list}`, { parse_mode: 'Markdown' });
});

bot.command('shell', async (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  const command = ctx.message.text.replace('/shell ', '').trim();
  if (!command) return ctx.reply('Usage: /shell <command>');
  ctx.reply(`⚡ Menjalankan: \`${command}\``, { parse_mode: 'Markdown' });
  const output = await runShell(command);
  ctx.reply(`\`\`\`\n${output.substring(0, 3000)}\n\`\`\``, { parse_mode: 'Markdown' });
});

bot.command('help', (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  ctx.reply(
    `*Hermes Agent Commands:*\n\n` +
    `/start — Sambutan\n` +
    `/model — Lihat model aktif\n` +
    `/shell <cmd> — Jalankan bash langsung\n` +
    `/wallets — Lihat semua wallet\n` +
    `/memory — Cek jumlah memory\n` +
    `/clearmemory — Hapus history chat\n` +
    `/status — Cek kesehatan semua service\n` +
    `/checkfix — Health check + auto-fix sekarang\n` +
    `/help — Bantuan ini\n\n` +
    `*Atau chat langsung:*\n` +
    `"clone repo https://github.com/..."\n` +
    `"buat 5 wallet ethereum"\n` +
    `"jalankan script /root/myscript.sh"\n` +
    `"cek disk usage"`,
    { parse_mode: 'Markdown' }
  );
});

// ─── MAIN MESSAGE HANDLER ─────────────────────────────────────────────────────
bot.on('message', async (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  const text = ctx.message.text;
  if (!text || text.startsWith('/')) return;

  console.log(`[MSG] ${text}`);

  // Load history
  let history = loadMemory();

  // Typing indicator
  await ctx.telegram.sendChatAction(ctx.chat.id, 'typing');

  try {
    // Tanya LLM dengan history
    const aiResponse = await askLLM(text, history);

    // Parse & eksekusi tools
    const { text: cleanText, toolOutputs } = await parseAndExecuteTools(aiResponse);

    // Simpan ke memory
    history.push({ role: 'user', content: text });
    history.push({ role: 'assistant', content: aiResponse });
    history = saveMemory(history);

    // Kirim response teks
    if (cleanText) {
      await ctx.reply(cleanText, { parse_mode: 'Markdown' }).catch(() => ctx.reply(cleanText));
    }

    // Kirim tool outputs
    for (const output of toolOutputs) {
      await ctx.reply(output, { parse_mode: 'Markdown' }).catch(() => ctx.reply(output));
    }

  } catch (error) {
    console.error('[ERROR]', error.message);
    ctx.reply(`❌ Error: ${error.message}`);
  }
});

bot.command('status', async (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  ctx.reply('🔍 Mengecek semua service...', { parse_mode: 'Markdown' });
  const report = await getStatusReport();
  ctx.reply(report, { parse_mode: 'Markdown' });
});

bot.command('checkfix', async (ctx) => {
  if (ctx.message.from.id !== OWNER_ID) return;
  ctx.reply('🔧 Menjalankan health check + auto-fix...', { parse_mode: 'Markdown' });
  await runAllChecks();
  ctx.reply('✅ Health check selesai! Lihat laporan di atas.', { parse_mode: 'Markdown' });
});

// ─── LAUNCH ───────────────────────────────────────────────────────────────────
bot.launch();
console.log('[Hermes] Bot launched');

// Init monitor setelah bot launch
initMonitor(bot, OWNER_ID);

process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
